# Generated by Django 3.1.4 on 2020-12-27 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bills', '0008_bill_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.bill')),
            ],
        ),
    ]
