# Generated by Django 3.1.4 on 2020-12-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_auto_20201225_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='from_data',
            new_name='from_date',
        ),
        migrations.AlterField(
            model_name='bill',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
