# Generated by Django 3.1.4 on 2020-12-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_auto_20201226_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='was_printed',
            field=models.BooleanField(default=True),
        ),
    ]
