# Generated by Django 3.1.4 on 2020-12-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0006_auto_20201226_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='last_printed',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
