# Generated by Django 3.1.4 on 2020-12-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0007_auto_20201226_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
