# Generated by Django 3.1.4 on 2020-12-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0008_bill_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_id',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
