# Generated by Django 3.1.4 on 2020-12-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0009_bill_bill_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='initial',
            field=models.BooleanField(default=True),
        ),
    ]
