# Generated by Django 3.1.4 on 2020-12-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='greeting',
            name='opening_template',
            field=models.TextField(default='Sehr geehrte Frau'),
            preserve_default=False,
        ),
    ]
