# Generated by Django 3.1.4 on 2020-12-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_greeting_opening_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='street_nr',
            field=models.CharField(max_length=5),
        ),
    ]
